4.4 Логирование и конфигурирование в приложении
VladBashlakov/third_course pull request #14
Opened 2022-03-23 21:54 UTC by VladBashlakov

2022-03-24 17:14 UTC, rmuhamedgaliev requested changes
Требуются правки 📝

2022-03-24 17:14 UTC, rmuhamedgaliev commented on src/main/java/ru/hogwarts/school/service/InfoServiceImplTest.java
> +    public String getPort() {
Тут немного неправильно, сделано. Ты должен научится считывать из properties файла параметры. И делать это через Value 
- https://www.baeldung.com/spring-value-annotation
- https://www.baeldung.com/properties-with-spring

2022-03-24 17:14 UTC, rmuhamedgaliev commented on src/main/java/ru/hogwarts/school/service/InfoServiceImplTest.java
> +    public String getPort() {
Суть задачи 

> В прошлом задании мы использовали свойство server.port. В этом пункте необходимо создать два конфигурационных файла. 

Считать параметр из разных файлов в зависимости от профиля. Поэтому в задании надо создать несколько конфигурационных файлов с разными параметрами - **server.port**

2022-03-25 21:26 UTC, rmuhamedgaliev requested changes
Требуются правки 📝

2022-03-25 21:26 UTC, rmuhamedgaliev commented on src/main/resources/application.properties
> +serverTest.port=9090
Это убрать, оно в спринге не используется

2022-03-25 21:26 UTC, rmuhamedgaliev commented on src/main/java/ru/hogwarts/school/service/InfoServiceImplTest.java
> +    @Value("${serverTest.port}")
Тут @Value("${server.port}")

2022-03-28 20:50 UTC, rmuhamedgaliev approved these changes
Принято ✅

2022-03-28 20:50 UTC, rmuhamedgaliev commented on src/main/java/ru/hogwarts/school/service/InfoServiceImpl.java
> +@Profile("production")
Тут не нужен профиль

2022-03-28 20:50 UTC, rmuhamedgaliev commented on src/main/resources/application-test.properties
> +server.port=9090
Не обязательно всегда все параметры переорпределять, можешь только необходимые. а тех что не хватает он возьмет из application.properties. В случае задания необходимо только **server.port** поменять

2022-03-28 20:50 UTC, rmuhamedgaliev commented on src/main/java/ru/hogwarts/school/service/InfoServiceImpl.java
> +@Profile("production")
Это только удали

2022-03-28 20:52 UTC, VladBashlakov commented on src/main/java/ru/hogwarts/school/service/InfoServiceImpl.java
> +@Profile("production")
ок)

2022-03-28 20:52 UTC, VladBashlakov commented on src/main/resources/application-test.properties
> +server.port=9090
понял)

2022-03-28 21:03 UTC, merged